# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTuu62lx-sT8U59wlsA46SFhUhGKCdEL
"""

import random

number_of_questions = 10
questions_answered = 0
correct = 0
for i in range(number_of_questions):
  print("This Program Has "+ str(number_of_questions)+ " Questions")
  max = 1001
  min = 0
  sub = 0
  a = random.randrange(1,1000)
  b = random.randrange(1,1000)
  if(a>b):
    max = a
    min = b
    print(a)
    print(b)
    sub = a-b
  else:
    max = b
    min = a
    print(b)
    print(a)
    sub = b-a
  print("please enter your answer:")
  val = input("Enter your value: ")
  print(sub)
  if(int(val) == sub):
    correct = correct+1
    print("Correct.")
  else:
    print("Correct Answer:"+str(sub))    
  print("Do you want to Continue?.....type y/n")
  con = input()
  if(con == "y"):
    questions_answered = questions_answered+1
  elif(con == "n"):
    break
print("Total number of questions:"+ str(number_of_questions))
print("Total number of question answered:" + str(questions_answered))
percentage_correct = (correct / questions_answered)*100
percentage_incorrect = ((questions_answered-correct)/questions_answered)*100
number_of_incorrect = questions_answered - correct
print("Total number of correct answer:"+str(correct))
print("Total number of incorrect answer:"+str(number_of_incorrect))
print("Total percentage of correct answer:"+str(percentage_correct))
print("Total percentage of incorrect answer:"+str(percentage_incorrect))
print("Bye Bye....")

a

